### ISSUE TITLE
[RESEARCH] Windows benchmark

### ISSUE THREAD

**Issue by sergeevabc** [Tinram/RND64#2]
rnd64 0.32

```
timer64 rnd64 -a 1G january
```
```c++
Kernel  Time =     1.326 =    6%
User    Time =    14.445 =   75%
Process Time =    15.771 =   82%    Virtual  Memory =   1028 MB
Global  Time =    19.207 =  100%    Physical Memory =   1030 MB
```

[dd](http://www.chrysocome.net/dd) 0.6b3

```
timer64 dd if=/dev/random of=february bs=1G count=1
```
```c++
Kernel  Time =     1.544 =   10%
User    Time =     1.653 =   11%
Process Time =     3.198 =   21%    Virtual  Memory =   1029 MB
Global  Time =    14.820 =  100%    Physical Memory =   1032 MB
```

Measured by [timer64](http://www.7-cpu.com/utils.html) 14.0.0

**Comment by Tinram** [comment]
Thank you for this profiling.

Can you also try:

    timer64 rnd64 -f 1G january

as this is the fastest switch, generating just zeros (without the overhead of random character generation).

Also for dd, /dev/random has blocking behavior.
Using /dev/urandom should be faster.

**Comment by sergeevabc** [comment]
[dd for Windows](http://www.chrysocome.net/dd) offers no ```urandom```.
And its ```random``` differs from Unix’s one, however device names are the same.
Basically we could say ```/dev/random``` = ```-a``` (but dd’s output is more dense) and ```/dev/zero``` = ```-f```.

```
timer64 rnd64 -f 1G march
```
```c++
Kernel  Time =     1.357 =   10%
User    Time =     0.249 =    1%
Process Time =     1.606 =   12%    Virtual  Memory =   1028 MB
Global  Time =    13.322 =  100%    Physical Memory =   1030 MB
```

```
timer64 dd if=/dev/zero of=april bs=1G count=1
```
```c++
Kernel  Time =     1.201 =    9%
User    Time =     0.374 =    2%
Process Time =     1.575 =   11%    Virtual  Memory =   1029 MB
Global  Time =    13.191 =  100%    Physical Memory =   1031 MB
```

**Comment by Tinram** [comment]
Sure.
Results are good.
Thank you for testing.
