### ISSUE TITLE
[FIXED] Memory limit

### ISSUE THREAD

**Issue by sergeevabc** [Tinram/RND64#3]
```rnd64 -a 4G filename``` makes system freeze if 4G is all RAM we have.

[dd](http://www.chrysocome.net/dd) 0.6b3 introduced a workaround ```dd if=/dev/random of=filename bs=1G count=4```, i.e. 1G×4=4G

**Comment by Tinram** [comment]
On your system, is this a total freeze or a temporary freeze?

The program and operating system should prevent the allocation of the (excessive) memory.
In testing on Windows and Linux, the program would bail out after a slight delay:

    aBuffer[i] = (char*) malloc(iBytesLocal + 1);
    if (aBuffer[i] == NULL) {
         fprintf(stderr, "\n%s: insufficient memory to allocate %"PRId64" bytes.\n\n", pFilename, iBytesLocal);

**Comment by sergeevabc** [comment]
I waited for a few minutes with OS being 100% busy (swapping as crazy, I guess), then killed the process.

**Comment by Tinram** [comment]
Yes confirmed: occurring on both Win 7 and Linux (with kernel 4.4).

I'm testing a cross-platform 'available' memory detector (currently more accurate on Windows via GlobalMemoryStatusEx() ).

**Comment by sergeevabc** [comment]
@Tinram, I advise you to try [mkrandom][1], it is very light on memory and lightning fast.

[1]: https://github.com/cohadar/mkrandom

**Comment by Tinram** [comment]
Good find.  Thank you.

**Comment by Tinram** [comment]
Memory issue on Windows fixed.
Memory issue on Linux: intermediate fix applied (until I find something better).
f4dcf0be0d81f95

Will try to integrate the mkrandom algorithm in a later release.

@sergeevabc - thank you for your help with this issue.

**Comment by Tinram** [comment]
The PCG RNG algorithm (as used by mkrandom) is incorporated into the program now.
The presence of multi-threading roughly doubles the generation speed of large stream sizes.

    mkrandom 4g | pv > /dev/null
    4GiB 0:00:01 [2.24GiB/s]

    rnd64 -a 4g | pv > /dev/null
    4GiB 0:00:01 [3.99GiB/s]

**Comment by sergeevabc** [comment]
Thank you for letting me know, @Tinram.
I verified it a few times during this summer and am happy with the results.
