### ISSUE TITLE
Wrong description for -a option

### ISSUE THREAD

**Issue by Vort** [Tinram/RND64#5]
Usage states that `-a` option gives range from 1 to 255:

https://github.com/Tinram/RND64/blob/5fc8445525e24bfd6cb0be8035607585c40d7183/src/rnd64.c#L679

Which is wrong: all possible byte values should give range from 0 to 255.

I checked generated files and they actually contain bytes in range from 0 to 255.

**Comment by Tinram** [comment]
Thank you @Vort 
You are correct.
Usage text corrected in version [_0.42_](https://github.com/Tinram/RND64/releases/tag/v0.42)

----

./rnd64 -f 1k | ./null_detect 
1024 null bytes found
1024 bytes parsed

./null_detect < f.txt
1024 null bytes found
1024 bytes parsed

./rnd64 -a 1k | ./null_detect 
8 null bytes found
1024 bytes parsed

**Comment by Tinram** [comment]
#5 closed.
